version: '3.8'

services:
  spark:
    build:
      context: ./spark
      dockerfile: Dockerfile
    volumes:
      - spark_data:/data
    networks:
      - dev_network

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    volumes:
      - airflow_data:/usr/local/airflow/dags
    networks:
      - dev_network

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    volumes:
      - jupyter_notebooks:/home/jovyan/work
    networks:
      - dev_network
    ports:
      - "8888:8888"

networks:
  dev_network:
    driver: bridge

volumes:
  spark_data:
  airflow_data:
  jupyter_notebooks: